[package]
name = "imesde-python"
version = "0.1.0"
edition = "2024"

[lib]
name = "imesde_python"
crate-type = ["cdylib"]

[dependencies]
imesde = { path = "../../core" }
pyo3 = { version = "0.23.3", features = ["extension-module"] }
