[package]
name = "imesde-python"
version = "0.1.0"
edition = "2024"

[lib]
name = "imesde"
crate-type = ["cdylib"]

[dependencies]
imesde = { path = "../../core" }
pyo3 = { version = "0.23.3", features = ["extension-module", "abi3-py310"] }
rayon = "1.11.0"
